lang_codes = {
  "Albanian" : "sq",
  "Bulgarian": "bg",
  "English": "en",
  "German": "de",
  "Hungarian": "hu",
  "Polish": "pl",
  "Portuguese": "pt",
  "Russian": "ru",
  "Serbo-Croatian": "sh",
  "Serbian": "sr",
  "Croatian": "hr",
  "Bosnian": "bs",
  "Slovak": "sk",
  "Slovenian": "sl",
  "Spanish": "es",
  "Swedish": "sv",
  "Arabic": "ar",
  "Chinese": "zh",
  "Hindi": "hi"
}